# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protocol.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Protocol.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0eProtocol.proto\"\x86\x01\n\x07\x43ommand\x12!\n\x06setPWM\x18\x01 \x01(\x0b\x32\x0f.Command.EngCtlH\x00\x12#\n\x08setSpeed\x18\x02 \x01(\x0b\x32\x0f.Command.EngCtlH\x00\x1a,\n\x06\x45ngCtl\x12\x13\n\x04side\x18\x01 \x01(\x0e\x32\x05.Side\x12\r\n\x05value\x18\x02 \x01(\x02\x42\x05\n\x03\x63md\"\x7f\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12*\n\nwheelState\x18\x01 \x01(\x0b\x32\x14.Feedback.WheelStateH\x00\x1a\x41\n\nWheelState\x12\x13\n\x04side\x18\x01 \x01(\x0e\x32\x05.Side\x12\r\n\x05speed\x18\x02 \x01(\x02\x12\x0f\n\x07mileage\x18\x03 \x01(\x02\x42\x04\n\x02\x66\x62\"L\n\tConfigPID\x12\t\n\x01p\x18\x01 \x01(\x02\x12\t\n\x01i\x18\x02 \x01(\x02\x12\t\n\x01\x64\x18\x03 \x01(\x02\x12\x0e\n\x06minOut\x18\x04 \x01(\x02\x12\x0e\n\x06maxOut\x18\x05 \x01(\x02\"6\n\x06\x43onfig\x12\x13\n\x0bticksPerSec\x18\x01 \x01(\x02\x12\x17\n\x03pid\x18\x02 \x01(\x0b\x32\n.ConfigPID\"\x1f\n\x07Point2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02*\x1b\n\x04Side\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01\x62\x06proto3'
)

_SIDE = _descriptor.EnumDescriptor(
  name='Side',
  full_name='Side',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=451,
  serialized_end=478,
)
_sym_db.RegisterEnumDescriptor(_SIDE)

Side = enum_type_wrapper.EnumTypeWrapper(_SIDE)
LEFT = 0
RIGHT = 1



_COMMAND_ENGCTL = _descriptor.Descriptor(
  name='EngCtl',
  full_name='Command.EngCtl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='Command.EngCtl.side', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Command.EngCtl.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=146,
)

_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setPWM', full_name='Command.setPWM', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setSpeed', full_name='Command.setSpeed', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COMMAND_ENGCTL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='cmd', full_name='Command.cmd',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=19,
  serialized_end=153,
)


_FEEDBACK_WHEELSTATE = _descriptor.Descriptor(
  name='WheelState',
  full_name='Feedback.WheelState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='Feedback.WheelState.side', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='Feedback.WheelState.speed', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mileage', full_name='Feedback.WheelState.mileage', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=276,
)

_FEEDBACK = _descriptor.Descriptor(
  name='Feedback',
  full_name='Feedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wheelState', full_name='Feedback.wheelState', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FEEDBACK_WHEELSTATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='fb', full_name='Feedback.fb',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=155,
  serialized_end=282,
)


_CONFIGPID = _descriptor.Descriptor(
  name='ConfigPID',
  full_name='ConfigPID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p', full_name='ConfigPID.p', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i', full_name='ConfigPID.i', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d', full_name='ConfigPID.d', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minOut', full_name='ConfigPID.minOut', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxOut', full_name='ConfigPID.maxOut', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=360,
)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticksPerSec', full_name='Config.ticksPerSec', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='Config.pid', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=416,
)


_POINT2D = _descriptor.Descriptor(
  name='Point2D',
  full_name='Point2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point2D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point2D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=449,
)

_COMMAND_ENGCTL.fields_by_name['side'].enum_type = _SIDE
_COMMAND_ENGCTL.containing_type = _COMMAND
_COMMAND.fields_by_name['setPWM'].message_type = _COMMAND_ENGCTL
_COMMAND.fields_by_name['setSpeed'].message_type = _COMMAND_ENGCTL
_COMMAND.oneofs_by_name['cmd'].fields.append(
  _COMMAND.fields_by_name['setPWM'])
_COMMAND.fields_by_name['setPWM'].containing_oneof = _COMMAND.oneofs_by_name['cmd']
_COMMAND.oneofs_by_name['cmd'].fields.append(
  _COMMAND.fields_by_name['setSpeed'])
_COMMAND.fields_by_name['setSpeed'].containing_oneof = _COMMAND.oneofs_by_name['cmd']
_FEEDBACK_WHEELSTATE.fields_by_name['side'].enum_type = _SIDE
_FEEDBACK_WHEELSTATE.containing_type = _FEEDBACK
_FEEDBACK.fields_by_name['wheelState'].message_type = _FEEDBACK_WHEELSTATE
_FEEDBACK.oneofs_by_name['fb'].fields.append(
  _FEEDBACK.fields_by_name['wheelState'])
_FEEDBACK.fields_by_name['wheelState'].containing_oneof = _FEEDBACK.oneofs_by_name['fb']
_CONFIG.fields_by_name['pid'].message_type = _CONFIGPID
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['Feedback'] = _FEEDBACK
DESCRIPTOR.message_types_by_name['ConfigPID'] = _CONFIGPID
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['Point2D'] = _POINT2D
DESCRIPTOR.enum_types_by_name['Side'] = _SIDE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {

  'EngCtl' : _reflection.GeneratedProtocolMessageType('EngCtl', (_message.Message,), {
    'DESCRIPTOR' : _COMMAND_ENGCTL,
    '__module__' : 'Protocol_pb2'
    # @@protoc_insertion_point(class_scope:Command.EngCtl)
    })
  ,
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'Protocol_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  })
_sym_db.RegisterMessage(Command)
_sym_db.RegisterMessage(Command.EngCtl)

Feedback = _reflection.GeneratedProtocolMessageType('Feedback', (_message.Message,), {

  'WheelState' : _reflection.GeneratedProtocolMessageType('WheelState', (_message.Message,), {
    'DESCRIPTOR' : _FEEDBACK_WHEELSTATE,
    '__module__' : 'Protocol_pb2'
    # @@protoc_insertion_point(class_scope:Feedback.WheelState)
    })
  ,
  'DESCRIPTOR' : _FEEDBACK,
  '__module__' : 'Protocol_pb2'
  # @@protoc_insertion_point(class_scope:Feedback)
  })
_sym_db.RegisterMessage(Feedback)
_sym_db.RegisterMessage(Feedback.WheelState)

ConfigPID = _reflection.GeneratedProtocolMessageType('ConfigPID', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGPID,
  '__module__' : 'Protocol_pb2'
  # @@protoc_insertion_point(class_scope:ConfigPID)
  })
_sym_db.RegisterMessage(ConfigPID)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'Protocol_pb2'
  # @@protoc_insertion_point(class_scope:Config)
  })
_sym_db.RegisterMessage(Config)

Point2D = _reflection.GeneratedProtocolMessageType('Point2D', (_message.Message,), {
  'DESCRIPTOR' : _POINT2D,
  '__module__' : 'Protocol_pb2'
  # @@protoc_insertion_point(class_scope:Point2D)
  })
_sym_db.RegisterMessage(Point2D)


# @@protoc_insertion_point(module_scope)
